SchweizerischeBundesbahnen/ch.sbb.polarion.extension.excel-importer

src/main/resources/webapp/excel-importer-admin/pages/about.jsp

fix: UTF-8 for about.jsp

---

.github/workflows/maven-release.yml

the repo was set to public and the artefacts can be released on Maven Central 

chore: turn on releases on Central Maven

---

pom.xml

feat: migration to generic v6.5.1

---

pom.xml

fix: migration to generic v6.5.2

---

.github/workflows/maven-build.yml
.pre-commit-config.yaml
README.md
docs/openapi.json
pom.xml

OpenAPI specification generate and added to docs folder

feat: OpenAPI Specification

---

.github/workflows/maven-build.yml

no comments in GitHub Actions Workflow

ci: workflow adjusted: no comments

---

.github/workflows/maven-build.yml

ci: fix upload github assets

---

docs/openapi.json
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/ExcelImportInternalController.java
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/WorkItemsInternalController.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ImportResult.java

Refs: #40
Extended REST API annotation

feat: Extended REST API annotation

---

docs/openapi.json
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/OpenAPIInfo.java

chore: Added OpenAPIInfo

---

.github/workflows/maven-build.yml
.github/workflows/openapi-validation.yml
.github/workflows/pr.yml
.github/workflows/release-please.yml
.pre-commit-config.yaml
CONTRIBUTING.md

ci: add OpenApi validator and sonar code coverage

---

README.md
docs/openapi.json
pom.xml
src/main/java/ch/sbb/polarion/extension/excel_importer/ExcelTool.java
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/ExcelImporterRestApplication.java
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/ExcelProcessingApiController.java
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/ExcelProcessingInternalController.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ExportHtmlTableResult.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ExportService.java
src/main/resources/META-INF/MANIFEST.MF
src/main/resources/META-INF/hivemodule.xml
src/test/java/ch/sbb/polarion/extension/excel_importer/ExcelToolTest.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ExportServiceTest.java

Refs: #75
Create separate endpoint & call it from velocity-generated code.

feat: export LiveDoc html table as xslx file

---

src/main/java/ch/sbb/polarion/extension/excel_importer/service/CellValue.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ExportService.java
src/main/resources/META-INF/MANIFEST.MF
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ExportServiceTest.java

hyperlink support for Excel cells

chore: hyperlink support for HTML table to Excel conversion

---

src/main/java/ch/sbb/polarion/extension/excel_importer/service/CellValue.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ExportService.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/htmltable/HtmlTableParser.java
src/main/java/ch/sbb/polarion/extension/excel_importer/utils/PolarionUtils.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ExportServiceTest.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/htmltable/HtmlTableParserTest.java
src/test/java/ch/sbb/polarion/extension/excel_importer/utils/PolarionUtilsTest.java

chore: images support for HTML table to Excel conversion

---

src/main/resources/webapp/excel-importer-admin/js/modules/import_file.js
src/main/resources/webapp/excel-importer-admin/js/modules/mappings.js
src/main/resources/webapp/excel-importer-admin/pages/import_file.jsp
src/main/resources/webapp/excel-importer-admin/pages/mappings.jsp
src/main/resources/webapp/excel-importer-admin/pages/modal.jsp

We have to use new generic features (JS modules).

chore: refactoring using js modules approach

---

docs/openapi.json
pom.xml
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ExportServiceTest.java

chore: change apache poi version to 5.4.0

---

pom.xml
src/main/java/ch/sbb/polarion/extension/excel_importer/settings/ExcelSheetMappingSettings.java
src/main/resources/webapp/excel-importer-admin/js/modules/import_file.js
src/main/resources/webapp/excel-importer-admin/js/modules/mappings.js
src/main/resources/webapp/excel-importer-admin/pages/import_file.jsp
src/main/resources/webapp/excel-importer-admin/pages/mappings.jsp
src/test/java/ch/sbb/polarion/extension/excel_importer/settings/ExcelSheetMappingSettingsTest.java

Refs: #100
We shouldn't show to user default global configuration.

feat: do not use global configuration

---

.github/workflows/maven-build.yml
pom.xml
src/main/resources/webapp/excel-importer/WEB-INF/web.xml

chore: migration to generic v10

---

src/main/java/ch/sbb/polarion/extension/excel_importer/service/ImportService.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ImportServiceTest.java

Refs: #118
We have to let user import new items where ID is mapped to workitem ID.

feat: import new items where ID is mapped to workitem ID

---

src/main/java/ch/sbb/polarion/extension/excel_importer/service/ImportService.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ImportServiceTest.java

fix: cannot invoke "Object.toString()" because link column id is null

---

src/main/java/ch/sbb/polarion/extension/excel_importer/service/htmltable/StyleContext.java
src/test/java/ch/sbb/polarion/extension/excel_importer/service/htmltable/StyleContextTest.java

Refs: #134
We must set 'TEXT' format by default to text cells.

feat: usage of 'TEXT' data format by default

---

pom.xml
src/main/java/ch/sbb/polarion/extension/excel_importer/rest/controller/ExcelProcessingInternalController.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ExportService.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/ImportService.java
src/main/java/ch/sbb/polarion/extension/excel_importer/service/parser/IParserSettings.java
src/main/java/ch/sbb/polarion/extension/excel_importer/utils/ExportXlsRunnable.java
src/main/java/ch/sbb/polarion/extension/excel_importer/utils/ParseXlsRunnable.java
src/main/resources/META-INF/MANIFEST.MF
src/test/java/ch/sbb/polarion/extension/excel_importer/service/ImportServiceTest.java
src/test/java/ch/sbb/polarion/extension/excel_importer/utils/ExportXlsRunnableTest.java
src/test/java/ch/sbb/polarion/extension/excel_importer/utils/ParseXlsRunnableTest.java

Refs: #148
Remove external Apache POI dependency and use latest version packaged into the extension bundle.

feat: use built-in Apache POI libraries
